README.md

Signed-off-by: Tracy Kuhrt <tkuhrt@linuxfoundation.org>

Populate README.md with contents of lab proposal

---

BUILD.md
PREREQUISITES.md

Signed-off-by: Byron Marohn <byron.marohn@intel.com>

Updated documentation for Ubuntu 18.04

---

eservice/lib/libpdo_enclave/base.edl
eservice/lib/libpdo_enclave/base_enclave.cpp
eservice/lib/libpdo_enclave/base_enclave.h
eservice/lib/libpdo_enclave/enclave_utils.h
eservice/pdo/eservice/enclave/enclave/base.cpp
eservice/pdo/eservice/enclave/enclave/base.h
eservice/pdo/eservice/enclave/enclave/enclave.cpp
eservice/pdo/eservice/enclave/enclave/enclave.h
eservice/pdo/eservice/enclave/enclave_info.cpp
eservice/pdo/eservice/enclave/enclave_info.h
eservice/pdo/eservice/utility/ias_client.py

pse occurrences have been cleaned up (sawtooth-side cleaning is a separate task)
test-request works successfully

pse cleanup

---

sawtooth/pdo_cli/pdo_cli_main.py

Signed-off-by: EugeneYYY <yevgeniy.y.yarmosh@intel.com>

fix for running pdo-cli without cmd line paramaters

---

PREREQUISITES.md

Signed-off-by: Byron Marohn <byron.marohn@intel.com>

Update URLs for openssl packages

---

PREREQUISITES.md
__tools__/rebuild.sh
docker/Dockerfile.pdo-dev

also change default ubuntu version to bionic (18.04), fix a /bin/sh vs /bin/bash bug and add missing dependency to pre-reqs

Update Docker to latest dependencies

---

PREREQUISITES.md
__tools__/rebuild.sh
docker/Dockerfile.pdo-dev
eservice/setup.py
pservice/CMakeLists.txt
pservice/setup.py

removed SGX_DEBUG variable

---

README.md

adding ppt presentation of PDO

---

__tools__/make-keys
common/crypto/pkenc_private_key.cpp
common/crypto/pkenc_private_key.h
common/crypto/sig_private_key.cpp
common/crypto/sig_private_key.h
common/interpreter/gipsy_scheme/SchemeExtensions.cpp
common/tests/testCrypto.cpp
common/tests/test_cryptoWrapper.py
eservice/lib/libpdo_enclave/enclave_data.cpp
pservice/lib/libpdo_enclave/enclave_data.cpp
python/pdo/common/keys.py

Signed-off-by: andrea miele <andrea.miele@intel.com>

Changed default constructor of private keys; introduced Generate()

---

__tools__/build/opt/pdo/etc/template/eservice.toml
__tools__/build/opt/pdo/etc/template/pcontract.toml
__tools__/build/opt/pdo/etc/template/pservice.toml
__tools__/make-config
client/etc/auction-test.toml
client/etc/sample_client.toml
client/pdo/client/scripts/AuctionTestCLI.py
client/pdo/client/scripts/CreateCLI.py
client/pdo/client/scripts/ShellCLI.py
client/pdo/client/scripts/UpdateCLI.py
eservice/etc/sample_eservice.toml
eservice/pdo/eservice/scripts/EServiceCLI.py
eservice/tests/etc/eservice_tests.toml
eservice/tests/test-contract.py
eservice/tests/test-request.py
pservice/etc/sample_pservice.toml
pservice/pdo/pservice/scripts/PServiceCLI.py

Clean up and canonicalize the ledger configuration. Provide a means to expand ${ledger} based on the LEDGER_URL environment variable.

Clean up the configuration of the ledger across all scripts

---

ethereum_preview/client/transaction_processor_client.py
ethereum_preview/contracts/transaction_processor.sol

Signed-off-by: Graziella <graziella.camata@intel.com>

Initial Ethereum implementation

---

PREREQUISITES.md

Signed-off-by: Byron Marohn <byron.marohn@intel.com>

Explicitly support only v2.2 of the SGX SDK

---

__tools__/build/opt/pdo/etc/template/eservice.toml
eservice/pdo/eservice/enclave/contract.cpp
eservice/pdo/eservice/enclave/enclave/base.cpp
eservice/pdo/eservice/enclave/enclave/base.h
eservice/pdo/eservice/enclave/enclave/contract.cpp
eservice/pdo/eservice/enclave/enclave/contract.h
eservice/pdo/eservice/enclave/enclave/enclave.cpp
eservice/pdo/eservice/enclave/enclave/enclave.h
eservice/pdo/eservice/enclave/enclave/enclave_queue.cpp
eservice/pdo/eservice/enclave/enclave/enclave_queue.h
eservice/pdo/eservice/enclave/enclave/signup.cpp
eservice/pdo/eservice/enclave/enclave_info.cpp
eservice/pdo/eservice/enclave/enclave_info.h
eservice/pdo/eservice/enclave/log.cpp
eservice/pdo/eservice/pdo_enclave.py
eservice/setup.py

Signed-off-by: Abdulkareem Adesokan <abdulkareem.adesokan@intel.com>

Multiple enclave workers managed by a queue

---

eservice/lib/libpdo_enclave/contract.edl
eservice/lib/libpdo_enclave/contract_enclave.cpp
eservice/lib/libpdo_enclave/contract_enclave.h
eservice/lib/libpdo_enclave/contract_request.cpp
eservice/lib/libpdo_enclave/contract_request.h
eservice/lib/libpdo_enclave/pdo_enclave.config.xml
eservice/pdo/eservice/enclave/enclave/base.cpp
eservice/pdo/eservice/enclave/enclave/base.h
eservice/pdo/eservice/enclave/enclave/enclave.cpp
eservice/pdo/eservice/enclave/enclave/enclave.h
eservice/pdo/eservice/enclave/enclave_info.cpp
eservice/pdo/eservice/enclave/enclave_info.h
eservice/pdo/eservice/pdo_enclave.py

Signed-off-by: Abdulkareem Adesokan <abdulkareem.adesokan@intel.com>

Implemented worker thread to init and cleanup gipsy interpreter

---

eservice/pdo/eservice/scripts/EServiceCLI.py
pservice/pdo/pservice/scripts/PServiceCLI.py

Signed-off-by: Abdulkareem Adesokan <abdulkareem.adesokan@intel.com>

Twisted now shuts down properly

---

eservice/pdo/eservice/enclave/enclave/enclave.cpp
eservice/pdo/eservice/enclave/enclave_info.cpp
eservice/pdo/eservice/enclave/enclave_info.h
eservice/pdo/eservice/pdo_enclave.py
eservice/pdo/eservice/pdo_helper.py
eservice/pdo/eservice/scripts/EServiceCLI.py
eservice/tests/test-contract.py
eservice/tests/test-request.py

Cleanly shutdown the enclave in tests and services

---

eservice/lib/libpdo_enclave/contract_enclave.cpp
eservice/lib/libpdo_enclave/contract_enclave.h
eservice/lib/libpdo_enclave/contract_request.cpp
eservice/lib/libpdo_enclave/contract_request.h
eservice/lib/libpdo_enclave/contract_worker.cpp
eservice/lib/libpdo_enclave/contract_worker.h
eservice/pdo/eservice/enclave/enclave/enclave.cpp

Pretty substantial performance improvement.

break out contract worker class and replace busy wait with explicit signals

---

build/Makefile
build/__tools__/expand-config

Remove redundant default setting, more centralization of configs

---

build/Makefile
build/__tools__/build.sh
build/common-config.sh
eservice/Makefile
eservice/bin/register-with-ledger.sh
eservice/bin/setup-contract-enclave-info.sh

moved the eservice scripts into the bin directory.
replaced the eservice info calls with the installed entry point
updated several of the build targets
added the build target to register the enclave signature with the ledger
build script now just builds, clean is separate
couple fixes in the config script

a few more build cleanups

---

common/state/state_kv.cpp

performance improvement (removed cache sync)

---

common/tests/state/CMakeLists.txt
common/tests/state/untrusted/test_cache.cpp
common/tests/state/untrusted/test_cache.h
common/tests/state/untrusted/test_state_kv.cpp

tests for cache existence and exaustion (disabled)

---

build/__tools__/run-tests.sh

Signed-off-by: Michael Steiner <michael.steiner@intel.com>

make test round-robin

---

eservice/pdo/eservice/enclave/contract.cpp
eservice/pdo/eservice/enclave/enclave_info.cpp
eservice/pdo/eservice/enclave/pdo_enclave.h
eservice/pdo/eservice/enclave/signup_info.cpp
eservice/pdo/eservice/enclave/swig_utils.cpp
eservice/pdo/eservice/enclave/swig_utils.h
eservice/pdo/eservice/pdo_enclave.py
eservice/pdo/eservice/scripts/EServiceCLI.py
python/pdo/service_client/storage.py

much smaller than normal. @bvavala should be happy.

small clean ups to logger, eservice and storage service client

---

README.md
build/tests/memory-test.exp
common/interpreter/gipsy_scheme/GipsyInterpreter.cpp
common/interpreter/gipsy_scheme/packages/init-package.scm
common/interpreter/gipsy_scheme/safe_malloc.cpp
common/log.h
common/packages/tinyscheme/opdefines.h
common/packages/tinyscheme/scheme-private.h
common/packages/tinyscheme/scheme.c
common/packages/tinyscheme/scheme.h

Small fix to the SAFE_LOG macro.
Small update per Tom's request to identify the project as a prototype.
Big update to clean up the tinyscheme interpreter.
Big performance boost.

Performance and documentation updates

---

build/__tools__/run-tests.sh
common/interpreter/gipsy_scheme/packages/catch-package.scm

Fix catch/throw Gipsy package for the lack of continuation support.

---

client/pdo/client/controller/commands/create.py
python/pdo/contract/contract.py
python/pdo/test/contract.py
python/pdo/test/request.py

Push contract tests into files with a unique name to avoid race condition #159

---

python/pdo/contract/contract.py

Let applications add data to the PDO file.

---

build/Makefile

Fix improper key reference in the build Makefile.

---

eservice/lib/libpdo_enclave/contract_secrets.cpp
eservice/tests/test-secrets.py

Fix #173 ensuring that there is one secret from each provisioning service

---

docker/Dockerfile.pdo-build
docker/README.md
docker/sawtooth-pdo.sgx.yaml
docker/sawtooth-pdo.yaml
eservice/lib/libpdo_enclave/contract_secrets.cpp
eservice/tests/test-secrets.py

- updated docu to make hopefully more user friendly
- garbage-collected some unnecessary sawtooth sdk builds
Signed-off-by: Michael Steiner <michael.steiner@intel.com>

Updated docker docu

---

build/__tools__/run-tests.sh

Clean up after the pdo-shell tests

---

build/__tools__/expand-config
build/__tools__/verify.sh
build/common-config.sh
build/keys/sgx_simulation/sgx_spid_api_key.txt
build/opt/pdo/etc/template/enclave.toml
docker/Dockerfile.pdo-build
docker/Makefile
docker/README.md
docker/sawtooth-pdo.sgx.yaml
eservice/docs/REQUIREMENTS.md
eservice/docs/test-scripts.md
eservice/etc/sample_eservice.toml
eservice/pdo/eservice/pdo_enclave.py
eservice/pdo/eservice/utility/ias_client.py
pservice/pdo/pservice/pdo_enclave.py
pservice/pdo/pservice/utility/ias_client.py

- changes to add IAS API-key based authentication (as defined in version 5.0 of IAS spec)
- should address issue #193 
PS: relative quick fix largely attributable to 4 OT nailbiter Blazer game asking for some distraction :-)

Support new IAS authentication mode

---

common/interpreter/ContractInterpreter.h
common/interpreter/gipsy_scheme/GipsyInterpreter.cpp
common/interpreter/gipsy_scheme/GipsyInterpreter.h
common/state/basic_kv.h
common/state/interpreter_kv.cpp
common/state/interpreter_kv.h
common/state/state_kv.cpp
common/state/state_kv.h
eservice/lib/libpdo_enclave/contract_code.cpp
eservice/lib/libpdo_enclave/contract_enclave.cpp
eservice/lib/libpdo_enclave/contract_request.cpp
eservice/lib/libpdo_enclave/contract_request.h
eservice/lib/libpdo_enclave/contract_response.cpp
eservice/lib/libpdo_enclave/contract_response.h
eservice/lib/libpdo_enclave/contract_state.cpp
eservice/lib/libpdo_enclave/contract_state.h

remove dynamic allocation in contract state

---

build/Makefile
build/__tools__/verify-pre-build.sh
build/__tools__/verify-pre-conf.sh
build/__tools__/verify.sh
build/common-config.sh
build/keys/sgx_hardware_mode/.gitignore
docker/Dockerfile.pdo-build
docker/Makefile
docker/sawtooth-pdo.sgx.yaml
eservice/bin/register-with-ledger.sh
eservice/pdo/eservice/scripts/EServiceEnclaveInfoCLI.py

Bye bye sawtooth hardcoded IAS key, let's grab it from IAS itself!

---

python/sawtooth/helpers/pdo_connect.py

Signed-off-by: prakashngit <prakash.narayana.moorthy@intel.com>

Fix for the problem of seeing INVALID transaction status from Sawtooth

---

common/interpreter/wawaka_wasm/README.md
docker/Dockerfile.pdo-dev
docs/environment.md

fix a specific WAMR version to use

---

common/interpreter/gipsy_scheme/packages/oops-package.scm

This is mostly prepartion for the interpreter API
unification. Replace error calls in the oops package
with catch/throw. Note that there may be some issues
with the different style of continuation handling in
the interpreter though all appears to be working.

Convert error calls in the oops package to throws.

---

.travis.yml
common/interpreter/wawaka_wasm/CMakeLists.txt
common/interpreter/wawaka_wasm/README.md
common/interpreter/wawaka_wasm/WawakaInterpreter.cpp
common/interpreter/wawaka_wasm/WawakaInterpreter.h
docker/Dockerfile.pdo-build

This PR also includes a few additional bug fixes.

Update Wawaka to WAMR-03-19-2020

---

common/interpreter/wawaka_wasm/WawakaInterpreter.cpp

When WAMR returns an error the result code is 0. This has some weird effects when address translation occurs and causes a SEGV. This protects the return processing from interpreter errors.

Protect parse return string from an error 

---

docker/Dockerfile.pdo-dev
docs/host_install.md
docs/install.md

Primarily updates the Dockerfile.

Upgrade PDO to SGX SDK 2.9.1

---

build/Makefile
contracts/wawaka/Makefile
contracts/wawaka/benchmarks/Makefile
docker/Makefile
eservice/Makefile
pservice/Makefile
python/Makefile

As discussed on CCF PR this morning ....

Adopted Makefiles to the more robust process concatenation done in prior CCF commit

---

.github/workflows/ci.yaml

Fix CI failures on new PRs

---

client/pdo/client/controller/commands/create.py
client/pdo/client/controller/contract_controller.py
python/pdo/common/utility.py
python/pdo/contract/code.py
python/pdo/contract/state.py

Adds some simple updates for the client shell processing.

Client Update

---

build/__tools__/run-tests.sh
client/pdo/client/controller/commands/eservice.py
docker/Dockerfile.pdo-dev
docker/README.md
docs/host_install.md
docs/install.md
docs/usage.md
python/pdo/contract/transaction.py
python/pdo/service_client/enclave.py
python/pdo/service_client/storage.py

several small fixes to make PDO run on ubuntu 20.04

---

build/common-config.sh
docker/Dockerfile.pdo-build
docker/Makefile

This PR disables Sawtooth -- it does *not* remove it.

Disable Sawtooth

---

build/tests/multi-user.sh
client/bin/pdo-invoke.psh
client/pdo/client/controller/commands/send.py
client/pdo/client/scripts/ShellCLI.py
contracts/wawaka/attestation-test/scripts/attestation-test.psh
docker/Dockerfile.pdo-build
eservice/pdo/eservice/enclave/enclave/enclave.cpp
eservice/pdo/eservice/enclave/enclave/enclave.h
eservice/pdo/eservice/enclave/enclave/signup.cpp
eservice/setup.py
pservice/lib/libpdo_enclave/secret_enclave.cpp
pservice/pdo/pservice/enclave/enclave/enclave.cpp
pservice/pdo/pservice/enclave/enclave/enclave.h
pservice/pdo/pservice/enclave/enclave/secret.cpp
pservice/setup.py
python/pdo/contract/transaction.py
python/pdo/submitter/ccf/ccf_submitter.py
python/setup.py

This PR is more of an appropriate size for @bvavala with several small fixes. It should be independent of the makefiles PR (meaning that they should be able to be applied in either order).

Several small fixes

---

README.md

Updated the README.md file with a link to the newly created pdo-contracts repository.

Updating readme.md with link to the pdo contracts repo

---

docker/tools/start_client.sh
docker/tools/start_services.sh

cleaning up a couple small bugs with docker tools

small docker fixes to fix loglevel switch in tools

---

docker/pdo_base.dockerfile

Update WAMR to 1.3.3 (released April of 2024).
Update WASI-SDK to 24 (released August of 2024).

Update WASM support 
