hyperledger-labs/private-data-objects

- __tools__/build/Makefile
- __tools__/build/opt/pdo/etc/template/pcontract.toml
- __tools__/rebuild.sh
- __tools__/run-tests.sh
- client/pdo/client/scripts/AuctionTestCLI.py
- client/pdo/client/scripts/UpdateCLI.py
- common/interpreter/gipsy_scheme/GipsyInterpreter.cpp
- common/interpreter/gipsy_scheme/GipsyInterpreter.h
- common/interpreter/gipsy_scheme/packages/oops-package.scm
- common/packages/tinyscheme/scheme.c
- eservice/lib/libpdo_enclave/contract_request.cpp
- eservice/lib/libpdo_enclave/contract_response.cpp
- eservice/lib/libpdo_enclave/contract_response.h
- eservice/tests/contracts/mock-contract-bad-expressions.exp
- eservice/tests/contracts/mock-contract-bad.scm
- eservice/tests/test-contract.py
- eservice/tests/test-request.py
- python/pdo/contract/response.py
Modify the result from contract method invocation to pass back
a status that captures the success/failure of the method execution.
On failure, only the result field will be filled, it will contain
the error message.
Client libraries for processing requests and results were modified
to accommodate the change return value. Client scripts were updated
as well to process the results.
Added a number of additional tests for bad messages. Added some
pdo-create and pdo-update tests including ones with bad contracts
and bad method expressions.
> Handle "cleanly" errors that occur in the contract interpreter during method evaluation

- eservice/lib/libpdo_enclave/contract_enclave.cpp
- eservice/lib/libpdo_enclave/contract_request.cpp
- eservice/lib/libpdo_enclave/contract_request.h
- eservice/lib/libpdo_enclave/contract_response.cpp
- eservice/lib/libpdo_enclave/contract_response.h
- eservice/lib/libpdo_enclave/contract_secrets.cpp
- eservice/pdo/eservice/enclave/enclave/contract.cpp
- python/pdo/contract/request.py
Replace all usages of EncryptMessage with user provided IV for AES-GCM encryption with calls to EncryptMessage  with no input IV and internally generated random IV.
> Fixed aes-gcm IV usage, all random now PDCN-210 

- client/contracts/contracts/integer-key.scm
- client/pdo/client/controller/__init__.py
- client/pdo/client/controller/commands/__init__.py
- client/pdo/client/controller/commands/contract.py
- client/pdo/client/controller/commands/create.py
- client/pdo/client/controller/commands/eservice.py
- client/pdo/client/controller/commands/pservice.py
- client/pdo/client/controller/commands/send.py
- client/pdo/client/controller/contract_controller.py
- client/pdo/client/controller/plugins/integer-key.py
- client/pdo/client/scripts/ShellCLI.py
- client/setup.py
- pservice/bin/ps-start.sh
NOTE: this depends on the build script improvement PR
This commit adds the pdo-shell interpreter for interacting with
private data objects. The shell provides some basic commands for
configuring provisioning and enclave services, managing identities,
creating & sending messages to contract objects.
In addition, the shell can be extended to provide per-contract class
extensions through a plugin system. And example plugin for the
integer-key contract is provided.
Finally, the shell can be scripted for execution through the command
line or through the shell prompt itself.
The details of the shell are still in flux. Documentation will follow
when the interface stabilizes.
> Implement a pdo-shell that supports contract-specific plugins

- sawtooth/bin/pdo-cli
PDCN-201
Import path parsing differs within and outside python virtual environment. 
Parsing within the environment is more restrictive.
Explicit import paths are added to fix the import parsing issue when running within the environment  
Signed-off-by: EugeneYYY <yevgeniy.y.yarmosh@intel.com>
> Fix to run pdo-cli from python virtual environment

- USAGE.md
- contracts/exchange/scripts/README.md
Fix links in the usage document that still referenced the old contract
layout. Also add links to the documentation for the exchange family of
contracts.
> Update documentation for the new contract structure.

- eservice/lib/libpdo_enclave/base_enclave.cpp
- eservice/lib/libpdo_enclave/contract_response.cpp
- eservice/lib/libpdo_enclave/contract_secrets.cpp
Dropped the logging level to debug for all of the statements in the
secrets module. Add the "debug" prefix to any variables that are created
exclusively for logging.
Added a critical message in enclave initialization to note that the
enclave was compiled with debugging on. Debug logging creates an obvious
channel that exposes confidential information.
> Clean up some of the enclave debugging to make it less verbose

- eservice/Makefile
- eservice/lib/libpdo_enclave/block_store.edl
- eservice/lib/libpdo_enclave/contract_response.cpp
- eservice/lib/libpdo_enclave/contract_state.cpp
- eservice/pdo/eservice/enclave/block_store.cpp
- eservice/pdo/eservice/enclave/block_store.h
- eservice/pdo/eservice/enclave/enclave/block_store.cpp
- eservice/pdo/eservice/enclave/enclave/block_store.h
- eservice/pdo/eservice/enclave/enclave/ocall.cpp
- eservice/pdo/eservice/enclave/pdo_enclave.h
- eservice/pdo/eservice/enclave/pdo_enclave_internal.i
- eservice/pdo/eservice/pdo_enclave.py
- eservice/pdo/eservice/pdo_helper.py
- eservice/pdo/eservice/scripts/EServiceCLI.py
- eservice/setup.py
- python/pdo/contract/request.py
- python/pdo/contract/response.py
- python/pdo/contract/state.py
- python/pdo/service_client/enclave.py
The block store is a state cache for the eservice which eliminates the
need to send state back and forth on every transaction. State is pulled
from the block store when running contracts, and the resulting state is
placed there when the contract execution completes.
Current implementation details:
- The block store is not persistent across restarts
- The client must retrieve state from the block store to store on the
ledger after any operation that updates the state
- The client must put the state block(s) into the block store when
starting work with an enclave service that does not currently have them.
Signed-off-by: Byron Marohn <byron.marohn@intel.com>
> Implemented enclave block store

- eservice/pdo/eservice/enclave/block_store.cpp
- eservice/pdo/eservice/enclave/block_store.h
> change return from block store init to avoid memory leak warning

- PREREQUISITES.md
- __tools__/build/opt/pdo/etc/template/eservice.toml
- common/CMakeLists.txt
- common/packages/block_store/lmdb_block_store.cpp
- eservice/etc/sample_eservice.toml
- eservice/pdo/eservice/scripts/EServiceCLI.py
- eservice/register_with_ledger.sh
- eservice/setup_contract_enclave_info.sh
- eservice/tests/etc/eservice_tests.toml
- Only run setup_contract_enclave_info.sh in HW Mode
- Make it more obvious when register_with_enclave.sh fails
- Dramatically reduce log spam from eservice
- Compile option to disable block store debug log messages
- LMDB maximum database size increased to 1 TB
- Reduce default number of enclave workers to 7
- Improve LMDB performance with MDB_WRITEMAP | MDB_NOMETASYNC
- Add lightning database package to PREREQUISITES
> Many small miscellaneous improvements

- python/pdo/contract/contract.py
- python/pdo/contract/request.py
- python/pdo/contract/response.py
- python/pdo/contract/state.py
No functional changes. State cache for blocks is still going
in the local directory only, ignoring the configuration.
> Refactor state moving all block retrieval into one place.

- eservice/pdo/eservice/pdo_enclave.py
- eservice/pdo/eservice/pdo_helper.py
- eservice/pdo/eservice/scripts/EServiceEnclaveInfoCLI.py
- eservice/register_with_ledger.sh
- eservice/setup_contract_enclave_info.sh
The scripts for processing enclave information were failing because the enclave was not shutdown cleanly. This should address that problem and cleans up the shell scripts.
> clean up the scripts that process enclave information

- __tools__/build/Makefile
- __tools__/build/opt/pdo/etc/template/enclave.toml
- __tools__/build/opt/pdo/etc/template/eservice.toml
- __tools__/build/opt/pdo/etc/template/pservice.toml
- __tools__/expand-config
- eservice/bin/es-start.sh
- eservice/pdo/eservice/scripts/EServiceCLI.py
- eservice/tests/test-contract.py
- eservice/tests/test-request.py
- eservice/tests/test-secrets.py
- pservice/bin/ps-start.sh
- pservice/pdo/pservice/scripts/PServiceCLI.py
- python/pdo/common/config.py
Multiple applications depended on the enclave module
configuration. All applications now share a single
enclave module configuration file.
To use effectively, this requires that two new environment
variables are set: PDO_SPID and PDO_SPID_CERT_FILE. If these
are not set, then the enclave configuration uses the old
default values.
> Move enclave module configuration to a single file

- common/crypto/crypto.h
- common/crypto/sgx_defaults.h
- docker/Dockerfile.pdo-dev
- eservice/lib/libpdo_enclave/contract.edl
- eservice/lib/libpdo_enclave/contract_enclave.cpp
- eservice/lib/libpdo_enclave/contract_secrets.cpp
- eservice/lib/libpdo_enclave/contract_secrets.h
- eservice/lib/libpdo_enclave/signup_enclave.cpp
- eservice/pdo/eservice/enclave/enclave/contract.cpp
- eservice/pdo/eservice/enclave/enclave/contract.h
- pservice/lib/libpdo_enclave/secret_enclave.cpp
This fix a major and a minor security issue with seal of contract state and unifies the settings for seal and attestation.
Note this will stop existing contracts from being read as sealkey changes!
> fix security issue with seal

- build/__tools__/run-tests.sh
- common/crypto/crypto_utils.cpp
- common/crypto/crypto_utils.h
- common/state/StateUtils.cpp
- common/state/StateUtils.h
- common/state/block_warehouse.cpp
- common/tests/testCrypto.cpp
- python/pdo/contract/state.py
- python/pdo/service_client/enclave.py
- python/pdo/test/__init__.py
- python/pdo/test/request.py
- python/pdo/test/state.py
this PR adds
-an HMAC wrapper to the crypto library
-tests for the HMAC function
-an authenticator field in the root block
-tests for checking whether the authenticator (and so the root block) is correct
-several fixes to make the tests work
-add another test in run-tests
> Root block authentication + related tests + related fixes

- build/Makefile
- build/__tools__/expand-config
- build/opt/pdo/etc/template/sservice.toml
- eservice/Makefile
- eservice/docs/sservice.md
- eservice/etc/sample_sservice.toml
- eservice/pdo/eservice/scripts/SServiceCLI.py
- eservice/setup.py
- python/pdo/service_client/__init__.py
- python/pdo/service_client/storage.py
- python/pdo/test/storage.py
This implements a storage service designed to run side-by-side with the
enclave service. The storage service shares an LMDB database with the
enclave service.
Several differences between the storage service and the storage interface
implemented in the enclave service. First, the storage service move binary
data for blocks in order to avoid the multiple levels of format translation
that occurs with the existing interfaces. Second, the storage service
provides bulk upload and status checks consolidating a number of operations
into a single call. Download is still one block at a time. Finally, the
storage service provides a signature for a bulk upload that can be used for
proof of replication.
This update does not integrate calls to the storage service into the clients
though it does provide …
> Implement the storage service

- build/__tools__/run-tests.sh
- build/opt/pdo/etc/template/pcontract.toml
- client/pdo/client/controller/commands/contract.py
- client/pdo/client/controller/commands/create.py
- client/pdo/client/controller/commands/send.py
- client/pdo/client/scripts/CreateCLI.py
- client/pdo/client/scripts/ShellCLI.py
- client/pdo/client/scripts/UpdateCLI.py
- client/pdo/client/scripts/__init__.py
- client/pdo/client/scripts/eservicedatabaseCLI.py
- client/setup.py
- eservice/docs/database.md
- eservice/docs/test-scripts.md
- python/pdo/common/utility.py
- python/pdo/service_client/__init__.py
- python/pdo/service_client/service_data/__init__.py
- python/pdo/service_client/service_data/eservice.py
- python/pdo/test/__init__.py
- python/pdo/test/contract.py
- python/pdo/test/request.py
- python/pdo/test/servicedb.py
The eservice database functionality is now provided via a functional interface instead of as a class as in the last PR. This PR replaces the last PR.  The data is stored as json. CLI is provided via the shell command pdo-eservicedb with command parameters such as create, add, remove, update.  Documentation can be found in eservice/docs/. New tests have been added to run-tests.sh to show the usage of the database for pdo test scripts.
Signed-off-by: prakashngit <prakash.narayana.moorthy@intel.com>
> Eservice database changes addressing comments

- build/__tools__/run-perf-tests.sh
- build/__tools__/run-tests.sh
- docker/Dockerfile.pdo-build
- docker/Dockerfile.pdo-dev
- docker/Makefile
- eservice/bin/es-status.sh
- eservice/bin/ss-status.sh
- pservice/bin/ps-status.sh
- make scripts a bit more robust and docker-friendly
- some cleanup of docker files
- warning that running docker test from a repo might run out of diskspace if you have (a) in-repo-built (build/_dev/...) installation and (b) run some tests with lingering lmdb-files
Signed-off-by: Michael Steiner <michael.steiner@intel.com>
> Docker related improvement

- build/__tools__/run-perf-tests.sh
- build/__tools__/run-tests.sh
- docker/Makefile
- docker/README.md
- eservice/bin/common.sh
- eservice/bin/es-start.sh
- eservice/bin/es-status.sh
- eservice/bin/es-stop.sh
- eservice/bin/ss-start.sh
- eservice/bin/ss-status.sh
- eservice/bin/ss-stop.sh
- eservice/setup.py
- pservice/bin/ps-start.sh
- pservice/bin/ps-status.sh
- pservice/bin/ps-stop.sh
- pservice/pdo/pservice/scripts/PServiceCLI.py
Address issue #182 and #164 :
- start detects already running service(s) and returns only
either after service(s) are up and running or a failure
- stop does work also with non-default ports and config-files
- fixes small bug in docker Makefile where wrong environment file was sourced
(omission from commit 7e4f29fe6883bfb43b1d4cf339ff1c8c66c35103)
> More robust service scripts

- LICENSE
- build/__tools__/clean.sh
- build/__tools__/verify.sh
- common/interpreter/gipsy_scheme/packages/build-init-package.sh
- common/interpreter/gipsy_scheme/packages/init-package.scm
- contracts/auction/Makefile
- contracts/bin/gipsyscheme
- contracts/exchange/Makefile
- contracts/integer-key/Makefile
- contracts/packages/debug.scm
- contracts/packages/init.scm
- contracts/test-contracts/Makefile
- docker/Dockerfile.pdo-dev
We have required three separate tinyscheme packages, one for gipsy
inside the enclave, one source install to build pcontract.so and
one for contract development outside the enclave. This update uses
the source install to build a scheme package that can be used for
development out of the enclave. A script (gipsyscheme) invokes the
scheme interpreter with the appropriate parameters & load files to
mimic (as closely as possible) the environment inside an enclave.
> Use the tinyscheme source to build the gipsy development interpreter.

- eservice/pdo/eservice/scripts/EServiceCLI.py
- pservice/pdo/pservice/scripts/PServiceCLI.py
Add some logging statements to get key information. Helps to debug problems with keys.
> Provide all the key information in the provisioning service info command

- build/Makefile
Currently, every time we build we overwrite the keys and configuration
files in the install directory tree.  This is rather inconvenient if you
have contracts that you want to keep running. This only builds the keys
and configuration files if they are missing or if the templates have
changed.
I'm sure there is other Makefile wizardry that could build implicit
rules for configuration files, but this works.
> Break out the build for keys and configuration files

- build/Makefile
- docker/Makefile
- add new target "force-conf" which forces new conf regardless whether files exist or not so we can force re-configuration if some variables like SPID has changed
- necessary, e.g., to make docker with SGX HW mode work again (of course, if i would have tested yesterday's PR not only with SIM but also HW, i would have found this issue already before i gave greenlight to merge that PR :-)
> Forced configuration regeneration

- build/__tools__/run-tests.sh
- build/opt/pdo/etc/template/pcontract.toml
- build/tests/shell-test.psh
- client/MANIFEST
- client/pdo/client/controller/commands/__init__.py
- client/pdo/client/controller/commands/contract.py
- client/pdo/client/controller/commands/create.py
- client/pdo/client/controller/commands/eservice.py
- client/pdo/client/controller/commands/eservice_db.py
- client/pdo/client/controller/commands/pservice.py
- client/pdo/client/controller/commands/send.py
- client/pdo/client/controller/contract_controller.py
- client/pdo/client/scripts/ShellCLI.py
- contracts/auction/integer-key-auction.py
- contracts/exchange/asset_type.py
- contracts/exchange/auction.py
- contracts/exchange/exchange.py
- contracts/exchange/issuer.py
- contracts/exchange/scripts/auction.psh
- contracts/exchange/scripts/create.psh
- contracts/exchange/scripts/create_eservice_db.psh
- contracts/exchange/scripts/exchange.psh
- contracts/exchange/scripts/issue.psh
- contracts/exchange/scripts/setup.sh
- contracts/exchange/vetting.py
- contracts/integer-key/integer-key.py
In preparation to remove the create, update and eservice database clients (so we only have one client to manager), this PR adds significant functionality to the pdo-shell. First, it incorporates the eservice database cleanly into the flow of the application (and adds operations to manage an eservice database). Second, it makes the shell "executable" (meaning that PSH scripts can be self-executing). Finally, it replaces a few of the existing scripts (specifically tests) with cleaner implementations.
> A number of enhancements to the pdo-shell, prepping to remove other clients

- build/__tools__/run-tests.sh
- build/opt/pdo/etc/template/pcontract.toml
- client/pdo/client/controller/commands/create.py
- client/pdo/client/controller/commands/send.py
- client/pdo/client/controller/contract_controller.py
- client/pdo/client/scripts/AuctionTestCLI.py
- client/pdo/client/scripts/CreateCLI.py
- client/pdo/client/scripts/ShellCLI.py
- client/pdo/client/scripts/UpdateCLI.py
- python/pdo/contract/__init__.py
- python/pdo/contract/contract.py
- python/pdo/contract/replication.py
- python/pdo/contract/request.py
- python/pdo/contract/response.py
- python/pdo/contract/state.py
- python/pdo/contract/transaction.py
- python/pdo/service_client/__init__.py
- python/pdo/service_client/storage.py
- python/pdo/test/contract.py
- python/pdo/test/request.py
This is a replacement for PR 205 (closed now).  This PR implements two features:
1.  Facility to replicate change-set (new blocks in the state after update) to the storage services associated with all provisioned enclaves for the contract
2. Facility to submit transactions asynchronously.
Both replication and transaction submission are performed after obtaining a response for the update operation being carried out. The two operations are together referred to as a commit operation. The client can simply invoke the commit operation (after obtaining the response to update operation) to carry out both replication and transaction submission asynchronously.  The client can any time in the future to check the status of the commit operation. The commit operation permits the client to specify past …
> New Replcation and transaction Modules

- eservice/Makefile
- eservice/bin/es-start.sh
- eservice/bin/es-stop.sh
- eservice/bin/ss-start.sh
- eservice/bin/ss-stop.sh
- eservice/pdo/eservice/scripts/EServiceCLI.py
- eservice/pdo/sservice/scripts/SServiceCLI.py
- pservice/Makefile
- pservice/bin/ps-start.sh
- pservice/bin/ps-stop.sh
- pservice/pdo/pservice/scripts/PServiceCLI.py
Replace the code that shutdown the service through an
HTTP request with a signal handler for SIGTERM. This
should ensure clean shutdown with greater security.
Addresses issued #165
> Change service shutdown to use signals #165

- client/pdo/client/controller/commands/create.py
- client/pdo/client/controller/commands/send.py
- client/pdo/client/scripts/CreateCLI.py
- client/pdo/client/scripts/UpdateCLI.py
- python/pdo/contract/response.py
- python/pdo/contract/transaction.py
- python/pdo/service_client/storage.py
- python/pdo/test/contract.py
- python/pdo/test/request.py
the commit_async API is simplified. Previously, there was a need to specify commit_dependencies explicitly via the API under special circumstances such as 1) when the contract state was loaded from a file, 2) when running multiple contracts with inter-contract dependencies. After the cleanup, all commit dependencies are automatically identified. In fact, commit_dependenciy specification is no longer part of the API, since everything is automatically identified.
Signed-off-by: prakashngit <prakash.narayana.moorthy@intel.com>
> simplifying API for the commit module 

- docker/Dockerfile.pdo-dev
- docker/Makefile
- docker/sawtooth-pdo.sgx.yaml
- docs/docker_install.md
- docs/host_install.md
- docs/install.md
This PR
* changes documentation to be based on latest DCAP infrastructure
* makes docker work on either DCAP or original SDK PSW installation
* It also bumps up docker to latest sgx sdk (2.6) and openssl 1.1.0 (1.1.0k) but does _neither_ update docker to dcap _nor_ update attestation to ECDSA, these will be later PRs ...
> DCAP infrastructure support

- .travis.yml
- common/tests/test_cryptoWrapper.py
- docker/Dockerfile.pdo-build
- docker/Dockerfile.pdo-dev
- docker/sawtooth-pdo.yaml
Subject more or-or-less says it all.  Two additional notes
- currently, gipsy is the default interpreter for docker but this can be changed via build-arg (or environment variable, if you run docker via docker/Makefile) PDO_INTERPRETER.  Note though that right now `make -C docker test` will fail (as expected) in run-tests.sh for wawaka. 
- for travis, the current config will run 'make -C docker test' for gipsy (i.e., runs clean build and all automated tests) and 'make -C docker test-env-setup` for wawaka (i.e., it runs all builds and unit-tests run as part of build, but does not run run-tests.sh as this fails for now).  Once we have unified run-tests for both wawaka and gipsy we can change it so for both interpreters all tests are executed as a PR-acceptance-test ...
PS: as "bonus" this PR …
> Docker support for wawaka  & continuous integration via travis

- common/interpreter/gipsy_scheme/SchemeExtensions.cpp
- common/interpreter/gipsy_scheme/tests/README.md
- common/interpreter/gipsy_scheme/tests/json.scm
- common/interpreter/gipsy_scheme/tests/test.scm
Added json-to-expression, expression-to-json and validate-json functions
to Gipsy. While this is in preparation for unifying the interpreter API
it also provides useful functions. Note that not all s-expressions can
be converted to JSON. Specifically:
- basic types, string, numbers, booleans are converted as expected
- symbols are not converted at all
- vectors are converted to vectors
- lists must be associative arrays, i.e. a list of two element lists; these are converted to a JSON object
Tests of the new functions are provided in the Gipsy tests directory.
> Add extensions functions to Gipsy to support conversion to/from JSON.

- common/interpreter/ContractCode.h
- common/interpreter/ContractMessage.h
- common/interpreter/invocation.json
- common/interpreter/wawaka_wasm/WawakaInterpreter.cpp
- common/interpreter/wawaka_wasm/WawakaInterpreter.h
- contracts/wawaka/common/Dispatch.cpp
- contracts/wawaka/common/Environment.cpp
- contracts/wawaka/common/Environment.h
- contracts/wawaka/common/Response.cpp
- contracts/wawaka/common/Response.h
- contracts/wawaka/common/Value.cpp
- contracts/wawaka/mock-contract/test-long.exp
- contracts/wawaka/mock-contract/test-short.exp
- contracts/wawaka/test-contract/test-contract.cpp
- contracts/wawaka/test-contract/test-short.exp
- eservice/lib/libpdo_enclave/contract_code.cpp
- eservice/lib/libpdo_enclave/contract_code.h
- eservice/lib/libpdo_enclave/contract_message.cpp
- eservice/lib/libpdo_enclave/contract_message.h
- eservice/lib/libpdo_enclave/contract_request.cpp
- eservice/lib/libpdo_enclave/contract_response.cpp
Primary contribution of this patch is the invocation specification. The specification defines the format of the JSON RPC that is made into the interpreter to invoke methods on the contract. It includes the format for the invocation request, invocation response, and the execution environment.
Implement the formal JSON RPC specification into the Wawaka interpreter. This requires a few changes to the interpreter and a large number of changes to the dispatch supporting routines.
One thing still missing and out of scope for this update: wawaka contracts do not have a way to access positional parameters.   
This commit also completes addition of dependency support for Wawaka contracts.
> Add invocation request/response formalization & implement in Wawaka

- README.md
- client/docs/BUILD.md
- common/BUILD.md
- common/README.md
- docs/docker_install.md
- docs/host_install.md
- docs/specification.md
- docs/usage.md
- eservice/docs/BUILD.md
- pservice/docs/BUILD.md
Addresses #241 
I would also recommend removing docs/docker_install.md since it is basically identical to docker/README.md.
> Fix broken links in docs

- common/state/cache.cpp
- common/state/cache.h
- common/state/data_node_io.cpp
- common/state/state_kv.cpp
- common/tests/state/untrusted/test.cpp
- common/tests/state/untrusted/test_cache.cpp
- common/tests/state/untrusted/test_cache.h
- common/tests/state/untrusted/test_state_kv.cpp
This PR improves the KVS as follows:
- it removes block write-back for read-only ops
- it removes the pre-allocation of a new append-block (which may not be needed)
- it includes tests with read-only operations for checking state hash invariance and zero state block write-backs 
> remove block write-back in KVS for read-only operations

- build/common-config.sh
- common/interpreter/wawaka_wasm/CMakeLists.txt
- common/interpreter/wawaka_wasm/README.md
- contracts/wawaka/CMakeLists.txt
This includes a new cmake function to automatically build the AoT-compiled contracts from wasm bytecode. Setting the `WASM_MODE=AOT` environment variable is currently a no-op.
> Add documentation for AoT-wasm support in Wawaka

- build/common-config.sh
- common/interpreter/wawaka_wasm/CMakeLists.txt
- common/interpreter/wawaka_wasm/README.md
- common/interpreter/wawaka_wasm/WawakaInterpreter.cpp
- docker/Dockerfile.pdo-build
- docs/environment.md
This new WAMR release allows us to enable the optimized WASM interpreter. The default wawaka execution mode is the "classic" un-optimized interpreter. The optimized interpreter mode can be enabled by setting the environment variable `WASM_MODE=INTERP_OPT`
> Update wawaka to WAMR-03-30-2020

- build/tests/wawaka/memory-test.json
- common/interpreter/wawaka_wasm/WawakaInterpreter.cpp
- common/interpreter/wawaka_wasm/WawakaInterpreter.h
This PR fixes the memory corruption bug due to large KV store values when running wawaka in `WASM_MODE=INTERP`. The test that are now fixed have been added to the memory-test suite.
> Fix INTERP mode memory corruption in WAMR

- common/interpreter/wawaka_wasm/README.md
- docker/Dockerfile.pdo-build
- docs/environment.md
This PR upgrades our WAMR submodule to the latest 04-15-2020 tag.
Notable updates to WAMR:
- Implement register/call native API with raw arguments
- Make heap and linear memory contiguous to refine compilation time and footprint
> Upgrade wawaka to latest WAMR-04-15-2020 tag

- contracts/wawaka/common/StringArray.cpp
- contracts/wawaka/common/StringArray.h
- contracts/wawaka/common/Util.h
- contracts/wawaka/common/Value.cpp
- contracts/wawaka/common/Value.h
Add method to validate structures, especially useful for
validating parameters to a method.
Fixes a bug where json_free may have been called twice
on a value. This may be the cause of the memory error
@masomel saw with clang.
> Add some functions to simplify contract building with wawaka

- common/log.h
- common/tests/state/untrusted/test_state_kv.cpp
This PR provides a useful tool for fine-grained memory usage tracking.
It leverages
* the standard `mallinfo` function in the untrusted environment, and 
* the `dlmallinfo` function in the trusted environment, which is available in the SGX SDK.
> mallinfo-based LOG_MEMORY define

- build/__tools__/expand-config
- build/common-config.sh
- ccf_transaction_processor/CMakeLists.txt
- ccf_transaction_processor/Makefile
- ccf_transaction_processor/README.md
- ccf_transaction_processor/etc/cchost.toml
- ccf_transaction_processor/scripts/configure_ccf_network.py
- ccf_transaction_processor/scripts/fetch_ledger_authority.py
- ccf_transaction_processor/scripts/generate_ledger_authority.py
- ccf_transaction_processor/scripts/ping_test.py
- ccf_transaction_processor/scripts/start_ccf_network.sh
- ccf_transaction_processor/scripts/start_cchost.sh
- ccf_transaction_processor/transaction_processor/pdo_tp.cpp
- ccf_transaction_processor/transaction_processor/pdo_tp.h
- python/pdo/submitter/ccf/ccf_submitter.py
1. Moved CCF tag to 0.11 from 0.9. Several API changes to address the move
2. ping_test can now be invoked from a remote machine where CCF is not installed.
Signed-off-by: prakashngit <prakash.narayana.moorthy@intel.com>
> CCF version moved to 0.11 from 0.9

- .dockerignore
- .travis.yml
- docker/Dockerfile.pdo-build
- docker/Dockerfile.pdo-dev
- docker/Dockerfile.pdo-tp
- docker/Makefile
- docker/sawtooth-pdo.proxy.yaml
- docs/host_install.md
- docs/install.md
- eservice/pdo/eservice/pdo_enclave.py
- eservice/pdo/eservice/pdo_helper.py
- eservice/pdo/eservice/scripts/EServiceEnclaveInfoCLI.py
Mostly an upgrade from 2.9.1 to 2.10 with additional pruning out of obsolete xenial/16.04 (non-)support while also laying the ground for 20.04.  Also a number of fixes and small clean-ups.
To make it work with HW mode, it also includes a commit with a bug-fix related CDI introduced in an earlier commit.
Lastly, due to some emsdk changes, fastcomp didn't build properly anymore in docker.  As a temporary "emergency" fix we install the (new) llvm backend.  However, as wawaka doesn't build yet with that backend, the corresponding travis builds are temporarily disabled in `.travis.yml`.
Note: while there is no complete sgx support yet for 20.04, it seems to be on its way (e.g., the modified binutils include 20.04 versions [even though in that case they shouldn't really be necessary as 20.04 …
> Upgrade to SGX 2.10 plus some ubuntu version clean-up

- .travis.yml
- common/interpreter/wawaka_wasm/README.md
- docker/Dockerfile.pdo-build
- docker/Dockerfile.pdo-dev
- docs/environment.md
This PR introduces two changes:
- Upgrade of the WAMR release used in Wawaka to `WAMR-07-10-2020`. No changes to Wawaka were needed.
- Explicit usage of the last emsdk release to support the fastcomp backend. Docker now checks out the `1.39.20` tag. This change is a workaround until we can stably support one of the newer WASM build toolchains.
> Updates to WASM toolchain

- contracts/wawaka/common/Cryptography.cpp
- contracts/wawaka/common/Cryptography.h
- contracts/wawaka/common/KeyValue.cpp
- contracts/wawaka/common/StringArray.cpp
- contracts/wawaka/common/StringArray.h
- contracts/wawaka/common/Util.cpp
- contracts/wawaka/common/Util.h
- contracts/wawaka/common/Value.cpp
- contracts/wawaka/common/Value.h
- contracts/wawaka/interpreter-test/interpreter-test.cpp
- contracts/wawaka/memory-test/memory-test.cpp
Add wrappers for the crytography and encoding extension functions
to use StringArray correctly.
Isolate all handling of memory from extension functions in a copy
from internal pointers. Currently this is set for safe mode (meaning
that we copy and free immediately) though a performant mode that
moves management of the pointers into StringArray.
Improve memory management in StringArray and Value.
Add "dot" operations for object retrieval in Value.
Add structures to Value.
> Update a number of the wawaka contract classes to improve memory management

- client/pdo/client/controller/contract_controller.py
In order to write scripts for the exchange family I need to
parse the JSON result and extract values. This pdo-shell
command eval's a python expression with the JSON dictionary
providing bindings.
> Add a pdo-shell command to parse a json string and extract a value

- common/interpreter/wawaka_wasm/README.md
- common/interpreter/wawaka_wasm/WawakaInterpreter.cpp
- docker/Dockerfile.pdo-build
- docs/environment.md
This PR brings Wawaka to the latest WAMR-09-29-2020 release, covering the previous WAMR-09-08-2020 tagged release as well. In these two releases, the WAMR team implemented additional post-MVP WASM features including support for libpthread and WASI (WebAssembly System Interface) in SGX, as well as several bugfixes. 
**Notes:**
- The `wasm_runtime_get_app_addr_range` API was changed since our last WAMR upgrade to use `uint32` instead of `int32` for the WASM address ranges.
- This PR still uses the latest-fastcomp emscripten backend.
> Upgrade to WAMR release WAMR-09-29-2020

- eservice/lib/libpdo_enclave/contract.edl
- eservice/lib/libpdo_enclave/contract_enclave.cpp
- eservice/lib/libpdo_enclave/contract_enclave.h
- eservice/pdo/eservice/enclave/enclave/base.cpp
- eservice/pdo/eservice/enclave/enclave/base.h
- eservice/pdo/eservice/enclave/enclave/contract.cpp
- pservice/pdo/pservice/enclave/enclave/base.cpp
- pservice/pdo/pservice/enclave/enclave/base.h
Subject should say it all.  Hopefully that fixes the random problems Prakash sees with the CCF PR ....
> Fix VerifySecrets ecall where we accidentally zero-padd short signatures

- build/tests/wawaka/interpreter-test.json
- common/interpreter/wawaka_wasm/WasmExtensions.cpp
- common/interpreter/wawaka_wasm/WasmExtensions.h
- common/interpreter/wawaka_wasm/WasmStateExtensions.cpp
- common/interpreter/wawaka_wasm/WasmStateExtensions.h
- common/interpreter/wawaka_wasm/WawakaInterpreter.cpp
- common/interpreter/wawaka_wasm/WawakaInterpreter.h
- contracts/wawaka/common/Cryptography.cpp
- contracts/wawaka/common/KeyValue.cpp
- contracts/wawaka/common/KeyValue.h
- contracts/wawaka/common/Util.h
- contracts/wawaka/interpreter-test/interpreter-test.cpp
- contracts/wawaka/interpreter-test/test-short.json
add create, open and finalize operations so that contracts can use key/value store that is distinct from the contract state. the basic idea is that data can be shared securely between contract objects. for example, the aggregator in a federated learning system could store the model in a separate store that could be shared to objects that update the model securely with local updates.
this feature is experimental. while minimal testing is provided in the commit, far more is necessary.
> experimental feature to allow an external kv store to be used by a contract object

- client/Makefile
- client/pdo/client/controller/contract_controller.py
- common/packages/parson/parson.cpp
- contracts/wawaka/common/Util.h
- eservice/Makefile
- pservice/Makefile
- python/Makefile
pdo-shell: add a raw flag to the echo command and process escapes by default (can use colors in echo statements)
parson: turn off escape of '/' in json serialization, the inconsistency with python handling causes no end of problems
wawaka macros: replace ASSERT_CONDTION with ASSERT_SUCCESS for a consistent way of testing conditions in contracts
> miscellaneous clean up and improvements

- client/bin/pdo-create.psh
- client/bin/pdo-invoke.psh
- client/pdo/client/controller/commands/create.py
- client/pdo/client/controller/commands/send.py
- client/pdo/client/controller/contract_controller.py
- client/pdo/client/scripts/ShellCLI.py
Add the ability to handle errors in subcommands. The command "trap_error"
will convert errors in commands from exceptions to successful returns. If
an error does occur, then the symbols "_error_code_" and "_error_message_"
will be set with the numeric code (generally -1) and error message from
the failed command. This is critical for writing negative tests (that is,
writing tests that are supposed to fail).
Enable the creation of script local bindings. In the past, the "script"
command operated on the current bindings. as a result, any changes in
the bindings made in the child script were transparently propogated to
the parent script. The new shell generally preserves that behavior, but
introduces a script local format for variables. In this case, any variable
that starts with '_' is …
> Update the pdoshell to handle errors and subprocesses more cleanly

- common/interpreter/wawaka_wasm/README.md
- contracts/wawaka/contract-build.cmake
- docker/Dockerfile.pdo-build
- docker/Dockerfile.pdo-dev
- docker/Makefile
- docs/environment.md
- docs/host_install.md
- docs/install.md
This PR upgrades the SGX SDK version to 2.13 and WAMR to the latest release tag `WAMR-01-29-2021`. Together these updates resolve the pthread-related issues we were seeing in #308. 
Notes:
- The changes in this PR have been tested in HW mode only on IceLake client with DCAP driver 1.41 (documentation updated to reflect this).
- This PR does not update the sgxssl version (yet).
> Upgrade to SGX SDK 2.13 and WAMR-01-29-2021

- common/crypto/verify_ias_report/build_ias_certificates_cpp.sh
The IAS root certificate has moved to a different location, so the build fails in HW mode.
This PR fixes the issue.
> Fix build of IAS certs

- common/interpreter/wawaka_wasm/README.md
- common/interpreter/wawaka_wasm/WasmExtensions.cpp
- common/interpreter/wawaka_wasm/WasmExtensions.h
- common/interpreter/wawaka_wasm/WawakaInterpreter.cpp
- common/packages/parson/parson.cpp
- contracts/wawaka/CMakeLists.txt
- contracts/wawaka/Makefile
- contracts/wawaka/benchmarks/fibonacci/fibonacci.cpp
- contracts/wawaka/common/Dispatch.cpp
- contracts/wawaka/common/KeyValue.h
- contracts/wawaka/common/Util.cpp
- contracts/wawaka/contract-build.cmake
- contracts/wawaka/exchange/scripts/run-tests.sh
- contracts/wawaka/interface-test/interface-test.cpp
- contracts/wawaka/interpreter-test/interpreter-test.cpp
- contracts/wawaka/mock-contract/mock-contract.cpp
- docker/Dockerfile.pdo-dev
- docker/README.md
Deprecate the use of emscripten for developing contracts for wawaka. We have struggled to support current version of emscripten. In an attempt to be more consistent with WAMR, this PR moves the toolchain to [WASI-SDK](https://github.com/WebAssembly/wasi-sdk). 
The migration enables the use of many classes from the C++ std library (strings, vectors, ...) which should make it significantly easier to write wawaka contracts.
> Migrate from emscripten to wasi-sdk for the wasm development tool chain

- common/interpreter/wawaka_wasm/README.md
- docker/Dockerfile.pdo-build
- docs/environment.md
This latest release implements auxiliary stack overflow/underflow check for WAMR in AOT/JIT/interpreter modes, implements a realloc wrapper in the builtin libc, and fixes several issues when using libpthread.
See https://github.com/bytecodealliance/wasm-micro-runtime/releases/tag/WAMR-04-15-2021 for the full release notes.
> Upgrade WAMR to WAMR-04-15-2021 release

- common/crypto/pkenc.h
This PR bumps the default RSA key size to 3072 bits as recommended by NIST. Moreover, this PR is motivated by the use of the PDO crypto lib by Fabric Private Chaincode, see corresponding [issue](https://github.com/hyperledger/fabric-private-chaincode/issues/478).
Signed-off-by: Marcus Brandenburger <bur@zurich.ibm.com>
> Bump RSA key size

- common/crypto/sig.h
This allows to define the elliptic curve used by the PDO crypto via the
-DPDO_USE_ECDSA_CURVE flag during compile time. When not defined, the
default curve is secp256k1 as used in BTC. This commit is motivated by
the use of the PDO crypto with Fabric Private Chaincode. In Fabric,
however, the default ellipctic curve is secp256r1 (aka prime256v1). This
compile flag allows to change the curve when used with FPC to be
complient with Fabric.
Signed-off-by: Marcus Brandenburger <bur@zurich.ibm.com>
> Make elliptic curve parameterizable

- .clang-format
- common/crypto/CMakeLists.txt
- common/crypto/verify_ias_report/verify-report.cpp
- common/crypto/verify_ias_report/verify-report.h
- common/tests/crypto/testCrypto.cpp
- pservice/lib/libpdo_enclave/secret_enclave.cpp
This PR contributes:
* an improved parsing of the json blob in the quote/report
* an extension to the report verification process to include additional SGX quote statuses
* a generalization of the policy-based verification procedure whereby users can specify whether to accept/reject specific quote statuses (among the `*_NEEDED` ones)
* tests related to the added/improved functionality
> Add policy-based verification of additional quote statuses

- build/Makefile
The build fails due to a recent update to the secp256k1 API which is used for Sawtooth.
We stick for now to the original old version.
> Fix secp256k1

- client/pdo/client/controller/contract_controller.py
- common/interpreter/wawaka_wasm/WasmCryptoExtensions.cpp
- common/interpreter/wawaka_wasm/WasmCryptoExtensions.h
- common/interpreter/wawaka_wasm/WasmExtensions.cpp
- common/interpreter/wawaka_wasm/WasmExtensions.h
- contracts/wawaka/attestation-test/attestation-test.cpp
- contracts/wawaka/attestation-test/scripts/attestation-test.psh
- contracts/wawaka/common/Attestation.cpp
- contracts/wawaka/common/Attestation.h
Add wawaka native function to parse the sgx quote and report
Add a function, sgx_parse_report, to convert the binary sgx report into a JSON structure that can be interpreted by the contract. Add a new common function package for processing the sgx attestation. Update the tests for the new values.
Also fix a bug in the error handling of pdo-shell.
> Implement wawaka function for parsing an SGX quote & report body

- ccf_transaction_processor/scripts/configure_ccf_network.py
- ccf_transaction_processor/scripts/fetch_ledger_authority.py
- ccf_transaction_processor/scripts/generate_ledger_authority.py
- ccf_transaction_processor/scripts/ping_test.py
- python/pdo/submitter/ccf/ccf_submitter.py
Temporary fix to skip checking CCF host certificate. . Version 0.11.7 CCF certificate expiration was hardcoded to the end of 2021. 
Signed-off-by: Prakash Narayana Moorthy <prakash.narayana.moorthy@intel.com>
> Temporary fix to skip checking CCF host certificate. 

- contracts/wawaka/attestation-test/attestation-test.cpp
- contracts/wawaka/attestation-test/plugins/attestation-test.py
- contracts/wawaka/attestation-test/scripts/attestation-test.psh
- contracts/wawaka/common/Dispatch.h
- contracts/wawaka/common/Secret.cpp
- contracts/wawaka/common/Secret.h
- contracts/wawaka/common/StateReference.cpp
- contracts/wawaka/common/StateReference.h
- contracts/wawaka/common/Util.h
- contracts/wawaka/common/contract/attestation.cpp
- contracts/wawaka/common/contract/attestation.h
- contracts/wawaka/common/contract/base.cpp
- contracts/wawaka/common/contract/base.h
- contracts/wawaka/contract-build.cmake
Two new classes of functions for the Wawaka common library:
- Secrets -- simplify (and standardize) generating messages that can be shared between contracts; a message is encrypted with the contracts encryption key.
- Attestation -- wrappers for the sgx report verification and processing functions
Add library of common wawaka contract methods.
There are several methods that are common to many contracts. This update provides a base implementation for those methods in order to simplify contract development.
Add common contracts methods for attestations.  Provides a wrapper for managing attested contract endpoints. Contract object provides an attestation package that is verified registering the encryption & verification keys for the contract. Useful for building contracts that share secrets. …
> More functions to simplify wawaka contract development

- .github/workflows/ci.yaml
The common config sets the default memory configuration
so we don't need to set it from here.
> Remove the redundant WASM_MEM config from github workflows

- contracts/wawaka/CMakeLists.txt
- contracts/wawaka/Makefile
- contracts/wawaka/contract-build.cmake
- contracts/wawaka/wawaka_common.cmake
Extends PR from @marcelamelara to separate contract compilation from building the common wawaka contract library. This should make it easier for others to build/extend the library.
> Make building wawaka common library configurable

- pservice/Makefile
This PR fixes a bug that was causing the pservice build to fail on ubuntu 20.04 machines due to a consistently reproducible race condition between cmake and make expecting enclave_u.c to exist before it was generated. This bug does not occur on ubuntu 18.04 or earlier.
Signed-off-by: Marcela Melara <marcela.melara@intel.com>
> Fix build bug in pservice in ubuntu20.04

- common/interpreter/wawaka_wasm/README.md
- docker/Dockerfile.pdo-build
- docs/environment.md
This PR bumps the WAMR release version up to the latest. Since the last WAMR release used (WAMR-04-15-2021), the latest WAMR releases provide enhancements and bug fixes for AoT compilation, as well as improvements to WAMR's use of WASI APIs and multithreading features.
PDO contract writers and PDO hosts should not expect any differences in functionality or usage of PDO with this upgrade.
WAMR release notes:
https://github.com/bytecodealliance/wasm-micro-runtime/releases/tag/WAMR-01-18-2022
https://github.com/bytecodealliance/wasm-micro-runtime/releases/tag/WAMR-12-30-2021
https://github.com/bytecodealliance/wasm-micro-runtime/releases/tag/WAMR-08-10-2021
> Upgrade wawaka to latest WAMR release WAMR-01-18-2022

- build/opt/pdo/etc/template/pcontract.toml
- client/pdo/client/controller/commands/create.py
- client/pdo/client/controller/commands/send.py
- client/pdo/client/scripts/ShellCLI.py
- eservice/MANIFEST
- eservice/pdo/sservice/__init__.py
- eservice/pdo/sservice/scripts/SServiceCLI.py
- eservice/pdo/sservice/wsgi/__init__.py
- eservice/pdo/sservice/wsgi/check_blocks.py
- eservice/pdo/sservice/wsgi/get_block.py
- eservice/pdo/sservice/wsgi/info.py
- eservice/pdo/sservice/wsgi/list_blocks.py
- eservice/pdo/sservice/wsgi/store_blocks.py
- eservice/tests/test-secrets.py
- python/pdo/common/block_store_manager.py
- python/pdo/common/config.py
- python/pdo/common/utility.py
- python/pdo/contract/contract.py
- python/pdo/contract/replication.py
- python/pdo/contract/response.py
- python/pdo/contract/state.py
- python/pdo/service_client/storage.py
- python/pdo/test/contract.py
- python/pdo/test/helpers/state.py
- python/pdo/test/request.py
- python/pdo/test/storage.py
PR includes two commits. 
The first makes the configuration globally accessible. A PDO client builds the configuration from files & command line switches and then pushes it into the global configuration. Services like the block store, file lookup, and replication manager can use it. Several strange defaults have been replaced with references to the global configuration.
The second commit moves the block store manager out of the storage service so that it can be used more generally. Specifically, the file system-based cache used by the client has been replaced with a cache based on the block store manager. This should simplify the process of managing the cache *as a cache*. Replaced several constants (that were overriding configuration file settings) with calls to the configuration …
> Blockstore and configuration updates

- bin/lib/common.sh
- build/Makefile
- build/__tools__/build.sh
- build/__tools__/clean.sh
- build/__tools__/run-benchmarks.sh
- build/__tools__/run-perf-tests.sh
- build/__tools__/run-tests.sh
- ccf_transaction_processor/scripts/start_ccf_network.sh
- ccf_transaction_processor/scripts/start_cchost.sh
- ccf_transaction_processor/scripts/stop_cchost.sh
- client/Makefile
- eservice/Makefile
- eservice/bin/es-start.sh
- eservice/bin/register-with-ledger.sh
- eservice/bin/ss-start.sh
- pservice/Makefile
- pservice/bin/ps-start.sh
- python/Makefile
This is preliminary support for clients running on ubuntu 22.04 where the python version is 3.10. Previously the regular expression used to get the version was limited to one digit minor versions. This should fix that limitation.
Note that shell scripts can use the check_python_version macro defined in the common.sh library.
> Change the python version regular expression for multi-digit versions

- common/interpreter/wawaka_wasm/README.md
- common/interpreter/wawaka_wasm/WawakaInterpreter.cpp
- docker/Dockerfile.pdo-build
- docs/environment.md
Key new features since last supported version (WAMR-01-19-2022):
- Since [WAMR-05-18-2022](https://github.com/bytecodealliance/wasm-micro-runtime/releases/tag/WAMR-05-18-2022)
* Implement Berkeley Socket APIs for libc-wasi and linux-sgx platforms
* Fix native stack overflow check failed in interpreter
* Fix various AOT compilation and loader issues
- Since [fast-jit-06-29-2022](https://github.com/bytecodealliance/wasm-micro-runtime/releases/tag/fast-jit-06-29-2022):
* First implementation of fast JIT
- Since [WAMR-1.0.0](https://github.com/bytecodealliance/wasm-micro-runtime/releases/tag/WAMR-1.0.0)
* Implement HW bound check for interpreter and Fast JIT
* Implement Python and go language bindings
* Enable SGX remote attestation using librats
* Add a new API to get free memory in memory …
> Upgrade wawaka to WAMR-1.1.2 release

- docker/Makefile
- docker/pdo.sgx.yaml
This PR renames sawtooth-pdo.sgx.yaml to pdo.sgx.yaml  so that the same file as can be used to mount sgx drivers when PDO is run in HW mode with CCF TP. Usage will come in the next PR
Signed-off-by: Prakash Narayana Moorthy <prakash.narayana.moorthy@intel.com>
> Renaming sawtooth-pdo.sgx.yaml to pdo.sgx.yaml 

- .github/workflows/ci.yaml
- docker/Dockerfile.pdo-dev
- docker/Makefile
- python/Makefile
This PR reduce the run time of the CI by ~30% by:
1. separating the tests for sawtooth and ccf, thus running them in parallel
2. removing the upgrade of the packages -- which was performed on all packages in pdo-dev, not just those necessary for PDO
3. redirecting the stdout/err of the sgxssl/openssl build to /dev/null -- importantly, this also reduces the CI logs from ~30K lines to **~8K lines**!!!
Additionally, it solves an issue with a duplicate build (of setup.py in /python).
The issue was caused by a misrepresented rule. The rule has 2 targets, which are all generated in one execution. However, by listing the 2 targets as dependencies and running make with multiple threads, make does not know that those targets should be grouped, so it runs the rule twice in parallel.
The result is a …
> Separate Sawtooth and CCF tests, speed up CI, reduce (unnecessary) logs and solve double build (with possible corruption) issue

- eservice/pdo/eservice/pdo_enclave.py
- eservice/pdo/eservice/utility/ias_client.py
- pservice/lib/libpdo_enclave/secret_enclave.cpp
- pservice/pdo/pservice/utility/ias_client.py
- sawtooth/common/pdo_signing.py
IAS v3 has reached end-of-life. Moving to v4 to support SGX HW mode.
Also, update flags in quote verification. Such more flexible policy evaluation allows to quote verification on Azure machines.
> Upgrade to IAS v4 and calibrate flags for Azure

- .github/workflows/ci.yaml
- bin/lib/common.sh
- bin/lib/common_service.sh
- build/Makefile
- build/__tools__/run-perf-tests.sh
- build/__tools__/run-tests.sh
- build/opt/pdo/etc/template/eservice.toml
- build/opt/pdo/etc/template/pservice.toml
- build/opt/pdo/etc/template/site.psh
- build/opt/pdo/etc/template/sservice.toml
- build/tests/multi-user.sh
- build/tests/shell-test.psh
- docker/Dockerfile.pdo-build
- docker/Dockerfile.pdo-dev
- docker/Makefile
- docker/ccf-pdo.proxy.yaml
- docker/ccf-pdo.yaml
- docker/ccf.proxy.yaml
- docker/pdo.sgx.yaml
- docker/sawtooth-pdo.proxy.yaml
- docker/sawtooth-pdo.yaml
Three big changes in this PR:
1. Dropped the "count" parameter from the service start up script; a service instance will now start for each of the configuration files in the configuration directory. And... the configuration directory is a parameter to startup. That should make it possible to separate "test" configuration from a "production" configuration.
2. Changed all the hard coded localhost references in the configuration files to PDO_HOSTNAME. We have the variable. Its supposed to be used. Now it is used.  And... the configuration files can be placed in an alternate directory. Again, goal is to simplify configuring a set of services for "production".
3. Fixed up a bunch of problems that popped up in docker tests. Turns out that the way we had the dockerfiles the hardcoded localhost …
> Start moving towards service startup that could be used for "production"

- common/interpreter/wawaka_wasm/README.md
- docker/Dockerfile.pdo-dev
- docker/README.md
- docker/ccf-pdo.proxy.yaml
- docker/ccf.proxy.yaml
- docs/install.md
This PR addresses #381 .
A couple of references still persist in the proxy yaml files.
As detailed in those comments, once we improve the proxy handling, those files should become obsolete and be removed.
> Clean up 18.04 references

- ccf_transaction_processor/scripts/start_cchost.sh
- ccf_transaction_processor/scripts/utils.py
- docker/Makefile
- docker/ccf-pdo.proxy.yaml
- python/pdo/submitter/ccf/ccf_submitter.py
The title is self-explanatory and the PR depends on #406.
Explanation.
(short)
CCF can be configured with a domain name, and the PDO legacy proxy handling works.
(long)
CCF is currently configured to use IPs. The main implication is that CCF generates certificates where x509 Subject Alternative Name is an IP address.
```
X509v3 Subject Alternative Name:
IP Address:192.168.192.2
```
Because of that, CCF clients have to use the IP address to contact it, otherwise the connection fails with an SSL error.
The PDO legacy proxy handling does not work in this case. The `no_proxy` variables are set up only with the `pdo-tp-ccf` domain name -- since clients are supposed to use the `pdo-tp-ccf:6600` ledger url. However, using the URL as-is would not work, as explained above, because the hostname …
> Make CCF HW mode work even with a proxy

- build/template/sservice.toml
- python/pdo/contract/replication.py
- sservice/etc/sample_sservice.toml
- sservice/pdo/sservice/scripts/SServiceCLI.py
- sservice/pdo/sservice/wsgi/info.py
- sservice/pdo/sservice/wsgi/store_blocks.py
The current policy for storage services is that the client determines the length of time a block will be stored. This is rather unrealistic. This makes the maximum duration a configuration parameter in the storage service and enforces the limit. The default value of 0 for the duration perserves the current behavior (the client determines the length of time the storage service will hold the block).
Note that this will require some adaptation when the replication policy is enforced by the ledger.
Also note that the automated tests are insufficient for testing at this point. The simplest test is to edit the test configuration files for sservice[2-5].toml and set the garbage collect interval to 1 and the max duration to 1, then run the services test.
> Allow replication service to limit the duration of cached blocks

- build/python_requirements.txt
- docker/Makefile
- docker/pdo_services_base.dockerfile
- docs/host_install.md
- docs/install.md
- eservice/lib/libpdo_enclave/enclave.edl
- pservice/lib/libpdo_enclave/enclave.edl
Update for OpenSSL 3.x. SGXSSL is still RC. Update when the final release is available.
> Update for OpenSSL 3.x, SGXSSL/SGXSDK 2.21

- build/template/pcontract.toml
- build/tests/multi-user.sh
- build/tests/service-test.sh
- client/bin/pdo-create-service-groups.psh
- client/pdo/client/builder/bindings.py
- client/pdo/client/builder/shell.py
- client/pdo/client/commands/service_db.py
- client/pdo/client/commands/service_groups.py
- client/pdo/client/scripts/ShellCLI.py
A few small updates to make the pdo-shell argument processing consistent with the other client applications (so they all use the same parameter processing function from pdo.client.builder.shell).  This update required some changes to the tests that invoke the shell. 
There are a couple of other small bug fixes included as well.
> Shell updates

- client/pdo/client/builder/installer.py
- eservice/pdo/eservice/scripts/EServiceCLI.py
- pservice/pdo/pservice/scripts/PServiceCLI.py
- sservice/pdo/sservice/scripts/SServiceCLI.py
A couple small fixes to the installer (to preserve mode bits) and the services (to enable configuration variable override).
> A couple random fixes for installer and service startup scripts

- build/__tools__/build.sh
- common/interpreter/wawaka_wasm/CMakeLists.txt
- common/interpreter/wawaka_wasm/README.md
- common/interpreter/wawaka_wasm/wamr_fixes.c
- common/packages/parson/parson.cpp
- common/packages/parson/parson.h
- contracts/wawaka/common/Util.cpp
- docker/pdo_base.dockerfile
This is not quite as simple as expected. With our
default configuration (LIBC on, WASI off) there are a couple errors in WAMR. Namely that os_is_handle_valid is not defined in sgx-platform.c and there is an include of libc_errno.h that appears to be outside the check for WASI includes.
Changes were made to work around these problems. Namely we explicitly include the libc header & source. And we add a file that defines the missing function.
> Update package dependencies: WAMR, WASI SDK, and parson

- docker/pdo_ccf.dockerfile
- docker/pdo_client.dockerfile
- docker/pdo_services.dockerfile
With warm pip-caches this did reduce docker build time on my laptop in WSL by more than half ...
BTW: mounting a pip-cache volume (`docker run -v $(DOCKER_DIR)/cache/pip:/project/pdo/.cache/pip ...`) also sped up ever more greatly testing of inference contract given the homogenously sized tensorflow packages ...
> Speed up docker (re-)build by caching pip cache

- docker/Makefile
- docker/base.yaml
- docker/ccf_base.yaml
- docker/client_base.yaml
- docker/make.dev
- docker/pdo_ccf.dockerfile
- docker/pdo_ccf_base.dockerfile
- docker/pdo_client.dockerfile
- docker/pdo_services.dockerfile
- docker/services_base.yaml
- docker/test.yaml
- docker/tools/bashrc_client.sh
- docs/docker.md
A few minor improvements in docker code to
- docker & docker-compose consistent
-  consistent tagging
-  build only via docker to prevent double builds
- consistent support of ADD_APT_PKGS
- some additional docker related make targets, e.g., additional stop targets, test without complete rebuild and _dev targets to setup development containers
- some minor dockerfile changes to be more consistent
BTW: in readme i've noticed we suggest in our examples to put user-name into container names. This seems a wise idea for multi-user settings. Should we also adopt it in the makefiles?  Easy to do but haven't changed it yet as i'm not sure if some other places count on the container names being what they are ...
Along the lines, the might include in name in container (and, more importantly, image) …
> Some minor docker improvements

- bin/Makefile
- build/Makefile
- docker/make.dev
- docker/pdo_ccf_base.dockerfile
- docker/tools/build_ccf.sh
- docker/tools/build_client.sh
- docker/tools/build_services.sh
- docker/tools/environment.sh
- docker/tools/run_ccf_tests.sh
- docker/tools/run_services_tests.sh
- docker/tools/start_ccf.sh
- docker/tools/start_services.sh
- ledgers/ccf/Makefile
- ledgers/ccf/scripts/start_ccf_network.sh
Several changes to improve the performance (and remove dependencies) for CCF startup. Many of the changes are centered in the ccf Makefile to separate the creation of the ccf clients (like the ping test, ledger authority retrieval and policy scripts that might reasonably be executed from anywhere) from the environment needed for a ccf service node (the script to start a ccf network).
The big win from the separation is that we can remove dependency on the sandbox script & pre-install all of the python package dependencies independently from the execution of the ccf nodes. The result is that the ledger containers start in a couple seconds instead of several minutes.
Note that a future PR will package the ccf client scripts separately and install them with other PDO packages so they are …
> Simplify build and install for CCF

- client/MANIFEST
- client/docs/collection.md
- client/pdo/client/commands/__init__.py
- client/pdo/client/commands/collection.py
- client/pdo/client/scripts/EntryPoints.py
- client/setup.py
- python/pdo/common/utility.py
Often a contract is meaningful only in the context of other contracts. For example, an asset issuer contract object may depend upon an asset type contract object. The type object is necessary to establish trust in the scope of the asset being issued.
In order to simplify sharing, a contract collection file packages information about a collection of contracts and their relationship to each other into a single bundle. The file that is created includes a context file that describes the relationships between the contracts and a list of contract description files that can be used to operate on the contract objects.
Note: collection operations are marked as experimental. Any use will generate a warning message when logging is turned on.
Details of the proposed functionality are found in Issue …
> Add an experimental command for importing and exporting collections of contracts

- docker/Makefile
Minor change to allow docker builds out-of-the-box without any configuration/environment variable definition.  This default for PDO_SOURCE_ROOT also hides an error for undefined `PDO_SOURCE_ROOT` which is _very_ unintuitive to figure out if you haven't run into this issue beforehand.
> Provide PDO_SOURCE_ROOT default for docker to allow zero-config build

- python/pdo/service_client/service_data/service_data.py
Small changes to fix several problems with the way last_verified_time is handled in the service data store. Improves variable naming and ensures that the value of last_verified_time is pushed through.
> Fix several bugs in the service data routines for verification

- ledgers/ccf/pdo/ledgers/ccf/scripts/ping_test.py
loguru warning method is warning() and not warn()
> Minor bug fix in the ping test module used by CCF. 

- docker/Makefile
Discovered testing [PDO contracts PR #32](https://github.com/hyperledger-labs/pdo-contracts/pull/32), see this [comment](https://github.com/hyperledger-labs/pdo-contracts/pull/32#issuecomment-2061716452)
> Build dependency bug fix

- common/crypto/sig_public_key.cpp
- eservice/pdo/eservice/scripts/EServiceCLI.py
- pservice/pdo/pservice/scripts/PServiceCLI.py
- pservice/test/UnitTests.py
- python/pdo/common/logger.py
- python/pdo/common/utility.py
- python/pdo/common/wsgi.py
- python/pdo/contract/contract.py
- python/pdo/contract/message.py
- python/pdo/contract/request.py
- python/pdo/service_client/enclave.py
- python/pdo/service_client/generic.py
- python/pdo/service_client/provisioning.py
- python/pdo/service_client/storage.py
- python/pdo/test/contract.py
- python/pdo/test/storage.py
- sservice/pdo/sservice/scripts/SServiceCLI.py
This PR addresses #288  and #484 .
> Fix assert statements and deprecated logger.warn's

- docker/Makefile
- docker/make.dev
Upstream docker doesn't work anymore with (ubuntu) docker-compose and relies now on a docker plugin (invoked as `docker compose`).  To enable both, parameterized invocation of docker-compose (and for consistency also docker) so upstream user can redefine `DOCKER_COMPOSE_COMMAND` to `docker compose` in `make.loc`
> Parameterize docker(-compose) commands

- ledgers/ccf/transaction_processor/pdo_tp.cpp
- pservice/lib/libpdo_enclave/secret_enclave.cpp
Adding comments to pdo tp and pservice code where enclave ias attesta…tion verification report is checked. Adding notes about the fact that currently we do not check whether the enclave runs in SGX debug mode or not. The corresponding issue can be found at https://github.com/hyperledger-labs/private-data-objects/issues/195
> Add comments to SW to address concerns in Issue 195

- client/pdo/client/builder/context.py
- client/pdo/client/commands/collection.py
- eservice/pdo/eservice/scripts/EServiceCLI.py
- eservice/pdo/eservice/scripts/EServiceEnclaveInfoCLI.py
- ledgers/ccf/setup.py
- pservice/pdo/pservice/scripts/PServiceCLI.py
- python/pdo/contract/response.py
- python/pdo/contract/transaction.py
- sservice/pdo/sservice/scripts/SServiceCLI.py
Several small python clean ups. 
Only significant behavior change would be in contract collections where top level contexts will not be expanded. Which means that references in the contexts will be preserved.
> Several small cleanups

- contracts/wawaka/contract-build.cmake
- docker/Makefile
Add HEADERS and LIBRARIES parameters to the contract build script. This makes it possible to customize each contract without changing the global WASM options.
Added some documentation.
> Extend the contract build cmake script to include custom libraries and headers

- .github/workflows/configured_test.yml
- .github/workflows/docker.yml
- .github/workflows/full_test.yml
*EXPERIMENTAL* -- new github workflows will only be visible and runnable when they are attached to the main branch. this commit will enable further testing.
Expand the github workflows associated with the PDO repository. The old "ci" workflow has been moved to a workflow called "full_test" and is used as a condition for merge of PRs. It will no longer be run on every push but only on PR creation and synchronization (when updates are pushed).
Add a "configured_test" workflow that can be dispatched on demand. This workflow allows for different build and run parameters to be set interactively.
Add a "build_docker" workflow that will attempt to build docker images pdo_client, pdo_services and pdo_ccf when a PR is merged successfully. This workflow can also be dispatched interactively.
> Updates to github workflows for PDO

- .github/workflows/docker.yml
Explicitly set the user and group ids for images that will be pushed ghcr by the docker workflow. This makes it easier to manage permissions of the xfer directory when using images from the registry.
> Set UID and GID for github generated docker images

- docker/README.md
- docker/base.yaml
- docker/ccf_base.yaml
- docker/client_base.yaml
- docker/configured_services.yaml
- docker/pdo_base.dockerfile
- docker/pdo_ccf.dockerfile
- docker/pdo_ccf_base.dockerfile
- docker/pdo_client.dockerfile
- docker/pdo_services.dockerfile
- docker/pdo_services_base.dockerfile
- docker/services_base.yaml
- docker/test-sgx.yaml
- docker/test.yaml
This PR cleans up the user and group creation in the docker build. An account and group are created in the base images and then used more consistently throughout the rest of the build process.
Added documentation for how to build and deploy "reusable" images that might be store, for example, in a public registry. This information should make it easier to use the images being built on github.
There are also some additions the docker cache for apt packages. 
Testing: automated tests should handle the changes to the docker build scripts. The instructions in the docker README.md for building deployable images (the final pattern) should be verified.
> Improvements for docker user management and documentation
